version: '3.7' #version of docker
services:
  hello-world-sb:
    build:
      context: . #use the current folder
      dockerfile: Dockerfile #Name of the docker file
    ports:
      - "8082:8082"
    restart: always
    depends_on: # Start the depends_on first
      - mysql
    environment:
      DATABASE_HOSTNAME: mysql  # Should be same as the service name
#      DATABASE_PORT: 3307
      DATABASE_NAME: hello_world_poc # database variable for application.properties
      DATABASE_USERNAME: user # database username variable for application.properties
      DATABASE_PASSWORD: password # database password variable for application.properties
    networks:
      - hello-world-springboot #Custom network

  mysql:
    image: mysql:5.7 #base image
#    ports:
#      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: hello_world_poc
    volumes:
      - mysql-database-data-volume:/var/lib/mysql #mysql folder inside host that contains data
    networks:
      - hello-world-springboot #Custom network

# Volumes
volumes:
  mysql-database-data-volume:

#Custom network
networks:
  hello-world-springboot: